### ISSUE TITLE
Checklist of items in preparation for 8.4.0

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5190]
This issue will be a running list of things to do as we countdown toward 8.4.0.  
#### Pull requests need to be renamed toward user synopsis
- [x] #4920 @lgu1234 
- [x] #4937 @JasonGlazer 
- [x] #5028 @rglazer2 
- [x] #5084 @rglazer2 
- [x] #5107 @rraustad 
#### Remaining code to merge or change milestone
- [x] #5218
- [x] #5213
- [x] #5191 
- [x] #5192
- [x] #5214
- [x] #5182 
#### Documentation work
- [x] Remove "cover pages"?
- [x] Copyright in Acknowledgements
- [x] ~~Fix tables in documentation (borders...)~~ tabled; opened #5240 
- [x] ExternalInterface: several missing braces, and "Can't load web font TeX/Main/Bold"
- [x] Update final documentation in https://github.com/nrel/EnergyPlusBuildSupport/tree/v8.4.0
#### Some other things
- [x] Mac package doesn't work
- [x] Update E+ Version in CMakeLists.txt
- [x] Update IDF version numbers
- ~~Get binary whitelisted ahead of release?~~ I have communicated with Kaspersky; will engage further if necessary
- [x] Test installation on all platforms; fresh machines and with previously installed versions
- [x] Do we need to change the ep-launch update url and or page?
- [x] Carry-over from #4532 to clean out some [preprocessor messages](https://github.com/NREL/EnergyPlus/issues/4532#issuecomment-78304488)
- [x] Change the 8.4.0 milestone on remaining items
- [x] Update epupdate anchor on energyplus.gov

**Comment by Myoldmopar** [comment]
Tested the 8.4.0 RC2 on Linux and ran an example file and everything looks OK so far.

**Comment by EnergyArchmage** [comment]
Tested EnergyPlus-8.4.0-1dc9d8f334-Windows-i386 on a Windows 8.1 machine and everything looks Okay.

**Comment by mitchute** [comment]
Tested EnergyPlus-8.4.0-1dc9d8f334-Windows-x86_64 on Windows 7SP1. Everything looks good. There were EP-Launch Version 8.3 warnings for the ExampleFiles\BasicFiles idf's.

**Comment by Myoldmopar** [comment]
Thanks @mmatts I fixed those version errors.  Getting close...
