### ISSUE TITLE
Max iteration and mass flow problems with WaterToAirHeatPump:VariableSpeedEquationFit

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5447]
- [x] Example file VSHeatPumpWaterToAirEquationFit has max iteration warnings, not converging on mass flow:
*MJW 2019-02-07 - these warnings are no longer there in v9.0.1, not sure when that got fixed.*

```
   ** Warning ** SimHVAC: Maximum iterations (20) exceeded for all HVAC loops, at CHICAGO_IL_USA ANNUAL HEATING 99% DESIGN CONDITIONS DB, 01/21 09:00 - 09:15
   **   ~~~   ** The solution for one or more of the Air Loop HVAC systems did not appear to converge
   **   ~~~   ** Air System Named = WAHP PACKAGE SINGLE ZONE 5 did not converge for mass flow rate
   **   ~~~   ** Check values should be zero. Most Recent values listed first.
   **   ~~~   ** Demand-to-Supply interface mass flow rate check value iteration history trace: 9.645979E-002,0.131420,0.179468,0.246017,0.339308,0.321195,9.645979E-002,0.131420,0.179468,0.246017,
   **   ~~~   ** Supply-to-demand interface deck 1 mass flow rate check value iteration history trace: 0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,
```

Output mass flow rate at the detailed timing reveals that the zone return node reports a different mass flow rate from the rest of the loop at certain times.  For example at  07/04  15:30:00

![image](https://cloud.githubusercontent.com/assets/4991075/12689401/4fe01236-c6a2-11e5-9930-b5ba3d997f14.png)

This file uses AirLoopHVAC:UnitaryHeatPump:WaterToAir with Coil:Heating:WaterToAirHeatPump:VariableSpeedEquationFit and Coil:Cooling:WaterToAirHeatPump:VariableSpeedEquationFit.  Several other files with the same coils also have max iteration warnings:
- [x] UnitarySystem_VSHeatPumpWaterToAirEquationFit _max iteration warnings gone after #5159_
- [ ] VSHeatPumpWaterToAirWithRHControl - *MJW 2019-07-02 - this file is covered by #6323*
- [x] HVACTemplate-5ZoneUnitarySystem (when run with design days or as annual), this one has siglespeed watertoair, and multispeed DX cooling, so this one may be a different issue _max iteration warnings gone after #5532_

**Comment by mjwitte** [comment]
@rraustad Not sure if this is related or not, but just recently another user working on his own custom version ran into max iteration issues with a multispeed dx coil and states that the problem appears to be in [ResolveAirLoopFlowLimits](https://github.com/NREL/EnergyPlus/blob/25aa84cae64103f392c383f01eb46724952b1d77/src/EnergyPlus/HVACManager.cc#L1786-L1820) if the main system starts with a lower airflow in early iterations and then tries to send a higher airflow, the terminal units don't honor the higher flow because the the maxavail doesn't get reset [here](https://github.com/NREL/EnergyPlus/blob/25aa84cae64103f392c383f01eb46724952b1d77/src/EnergyPlus/HVACManager.cc#L1846-L1849). But I have not verified this or tried a fix for it.

**Comment by rraustad** [comment]
The disconnect between the supply and demand side air flow rate is easily explained, yet not so easy to correct. If the final iteration is one that changes flow, the air loop supply and demand side will not be equal (at least in my mind,not sure if the code will or even tries to resolve all the way around the loop). These max iterations are starting to grate on me so I think I'll be paying a little more attention to the cause and resolution.

**Comment by mjwitte** [comment]
@rraustad The two VSHeatPumpWaterToAir\* files for this issue use AirLoopHVAC:UnitaryHeatPump:WaterToAir.  Wondering if that system has the same excess maxavail code that was removed from AirloopHVAC:UnitarySystem in #5532

**Comment by rraustad** [comment]
Furnaces.cc in SetAverageAirFlow:

```
// IF the furnace is scheduled on or nightime cycle overrides fan schedule. Uses same logic as fan.
if ( GetCurrentScheduleValue( Furnace( FurnaceNum ).SchedPtr ) > 0.0 && ( ( GetCurrentScheduleValue( Furnace( FurnaceNum ).FanAvailSchedPtr ) > 0.0 || TurnFansOn ) && ! TurnFansOff ) ) {
    Node( InletNode ).MassFlowRate = AverageUnitMassFlow;
    Node( InletNode ).MassFlowRateMaxAvail = AverageUnitMassFlow;
```

**Comment by rraustad** [comment]
VSHeatPumpWaterToAirEquationFit - Identical warnings with and without the MaxAvail line above.

```
** Warning ** SimHVAC: Maximum iterations (20) exceeded for all HVAC loops, at Chicago Ohare Intl Ap IL USA TMY3 WMO#=725300, 01/05 02:15 - 02:30
**   ~~~   ** The solution for one or more of the Air Loop HVAC systems did not appear to converge
**   ~~~   ** ...use Output:Diagnostics,DisplayExtraWarnings; to show more details on each max iteration exceeded.
** Warning ** SimHVAC: Maximum iterations (20) exceeded for all HVAC loops, at Chicago Ohare Intl Ap IL USA TMY3 WMO#=725300, 01/05 02:15 - 02:16
```

**Comment by rraustad** [comment]
Remove that line also in this branch? I guess it can't hurt, and probably masks the underlying cause.
("that line" = Node( InletNode ).MassFlowRateMaxAvail = AverageUnitMassFlow; in Furnaces::SetAverageAirFlow)

**Comment by mjwitte** [comment]
Closing this issue. #6323 covers the last remaining item from this one.
