### ISSUE TITLE
IDD Cleanup post v8.5

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5502]
- [x] In SurfaceContaminantSourceAndSink:Generic:BoundaryLayerDiffusion, this field name should be title case:

N2 ; \field Henry adsorption constant or partition coefficient

_Note that I/O Ref already has proper case._

**Comment by mjwitte** [comment]
- [x] @macumber commented [here](https://github.com/NREL/EnergyPlus/pull/5361#issuecomment-187269973) that it does not make sense for a field which has a \default to also be \required-field  The OpenStudio parser warns about these, would be useful to attach a list of those warnings here to help find all of these and remove the \required-field designation.

_Addressed in #5817. In nearly all instances, /required-field was removed, and if needed /min-fields was added or extended to ensure that the default would be filled in.  In a few isolated cases /required-field was kept, but the /default was removed if it was not meaningful, e.g. /default 0._

**Comment by mjwitte** [comment]
- [ ] The issue of required fields which have defaults was part of [broader question](https://github.com/NREL/EnergyPlus/pull/5361#issuecomment-164565257) about standardizing autosized fields, related to #5361 

Looking for examples of other autosized fields in the IDD, there are several flavors:

some are not required, no default
some are required, but no default
some are required and have default autosize
some are not required and have default autosize

We should agree on and document a standard policy for autosizable fields. Then fix all of them to be consistent.

I propose that they all be _not required_ and they should all _have a default_ of autosize or autocalculate as appropriate.

**Comment by mjwitte** [comment]
- [x] Add `\units Pa` to field N3 of Coil:Heating:WaterToAirHeatPump:ParameterEstimation (this was part of #5159 but will be removed from that PR so it can be merged for v8.5 without impacting the IDD).

**Comment by macumber** [comment]
Here is code that generates OpenStudio warnings:

```
require 'openstudio'

OpenStudio::Logger::instance().standardOutLogger().setLogLevel(OpenStudio::Debug)

idd = OpenStudio::IddFile::load('V8-3-0-Energy+.idd')
idd.get.objects.each do |object|
  # does nothing, just forces object to be parsed
  s = object.numFields 
end
```

**Comment by macumber** [comment]
Here is output when running on the 8.3 IDD

[out.txt](https://github.com/NREL/EnergyPlus/files/142971/out.txt)

**Comment by macumber** [comment]
- [x] _Addressed in #5504_ Our parser can't load the 8.4 IDD because of this object:

ZoneAirMassFlowConservation,
       \memo Enforces the zone air mass flow balance by adjusting zone mixing object and/or
       \memo infiltration object mass flow rates. 
       \memo If either mixing or infiltration is active, then the zone air mass flow
       \memo balance calculation will attempt to enforce conservation of mass for each zone.
       \note If mixing is "No" and infiltration is "None", then the zone air mass flow 
       \note calculation defaults to assume self-balanced simple flow mixing and infiltration objects.
       \unique-object
       \min-fields 3

The OpenStudio parser is very strict and only allows \memo properties at the object level and \note properties at the field level (that is what is documented in the IDD header)

**Comment by mjwitte** [comment]
@Myoldmopar Should we do a quick fix on the develop IDD to fix the mis-tagged note/memo issue?

**Comment by jasondegraw** [comment]
@mjwitte @Myoldmopar Would it be worth it to talk about a custom CI check of the IDD to catch these things automatically?

**Comment by mjwitte** [comment]
@jasondegraw Yes, please, go for it.

**Comment by Myoldmopar** [comment]
We can do a quick fix on the IDD for 8.5.0, yes, but that won't fix the 8.4.0 release IDD...

**Comment by mjwitte** [comment]
@macumber The issue of fields with both \required-field and \default has been fixed in #5817 based on the list you provided [above](https://github.com/NREL/EnergyPlus/issues/5502#issuecomment-187774318).  It would be great if you could run the revised IDD through the same script and let me know any of these were missed or if other errors pop up.

**Comment by macumber** [comment]
Also commented on the pull request, here are the current errors:

```
[utilities.idd.IddField] <1> Field is of type choice but keys are empty: 'Optical Data Type'
[utilities.idd.IddField] <-1> Field 'Optical Data Type' of object 'WindowMaterial:Glazing:EquivalentLayer' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Illuminance Setpoint at Reference Point' of object 'Daylighting:DELight:ReferencePoint' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Fraction of Zone Controlled by Reference Point' of object 'Daylighting:DELight:ReferencePoint' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Rated Sensible Heat Ratio at Speed 1' of object 'Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Rated Water Heating COP at Speed 1' of object 'Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Nominal Speed Level' of object 'Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Number of Speeds' of object 'Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Direct Pad Depth' of object 'EvaporativeCooler:Direct:CelDekPad' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Direct Pad Area' of object 'EvaporativeCooler:Direct:CelDekPad' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Direct Pad Depth' of object 'EvaporativeCooler:Indirect:CelDekPad' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Direct Pad Area' of object 'EvaporativeCooler:Indirect:CelDekPad' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Nominal Supply Air Flow Rate' of object 'HeatExchanger:AirToAir:FlatPlate' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Number of Compressor Loading Index Entries' of object 'AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Number of Compressor Loading Index Entries' of object 'AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl:HR' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'G-Function Reference Ratio' of object 'GroundHeatExchanger:Vertical' is both required and has default value, setting required = false.
[utilities.idd.IddField] <1> Field is not of type choice but has non-empty keys: 'Heat Exchange Model Type'
[utilities.idd.IddField] <-1> Field 'Heat Exchange Model Type' of object 'HeatExchanger:FluidToFluid' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Maximum Supply Temperature Setpoint' of object 'SetpointManager:ReturnTemperature:ChilledWater' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Minimum Supply Temperature Setpoint' of object 'SetpointManager:ReturnTemperature:ChilledWater' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Maximum Supply Temperature Setpoint' of object 'SetpointManager:ReturnTemperature:HotWater' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Minimum Supply Temperature Setpoint' of object 'SetpointManager:ReturnTemperature:HotWater' is both required and has default value, setting required = false.
[utilities.idd.IddField] <-1> Field 'Selection Control' of object 'DemandManager:Ventilation' is both required and has default value, setting required = false.
```

**Comment by Myoldmopar** [comment]
Closed via #5817
