### ISSUE TITLE
Documentation Issues - April-August 2016

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5603]
- [x] In the IDD, WeatherProperty:SkyTemperature, the Schedule Name field can accept either a day schedule or an annual schedule, but the object-list reference only points to day schedules.

```
  A3;  \field Schedule Name
       \required-field
       \note if name matches a SizingPeriod:DesignDay, put in a day schedule of this name
       \note if name is for a SizingPeriod:WeatherFileDays, SizingPeriod:WeatherFileConditionType or
       \note RunPeriod, put in a full year schedule that covers the appropriate days.
       \type object-list
       \object-list ScheduleAndDayScheduleNames
```

Suggest changing the above to two lines:

```
\object-list ScheduleNames
\object-list DayScheduleNames
```

Then delete the three occurences of \reference ScheduleAndDayScheduleNames

_Addressed in #5817_

**Comment by mjwitte** [comment]
- [ ] Engineering Reference, section 6.8.15.2 Equivalent Layer Optical Model, in the nomenclature list following figure 6.62, the variables which should be greek letters are not.  These were wrong also in the md version of the docs.  Refer back to v8.2 docs for the correct letters, following Figure 114 in that version.
- ***addressed in #5603***

**Comment by JasonGlazer** [comment]
- [x]  Add to Energy+.idd: AvailabilityManager:OptimumStart and AvailabilityManager:HybridVentilation as \key choices in the  AvailabilityManagerAssignmentList object

_Addressed in #5817. But AvailaiblityManager:HybridVentilation is not valid in the availability manager list, it hangs out there alone.  So only added keys for AvailiabilityManager:OptimumStart"._

**Comment by mjwitte** [comment]
- [ ] Dataset typo, see #5619 

- ***addressed in issue #5603 (as suggested).***

**Comment by mjwitte** [comment]
- [ ] Helpdesk ticket 11322, questions about modeling a shade layer in a four pane window.  The v8.5 I/O Ref, on p. 347 under WindowProperty:ShadingControl Shading Type implies that shading only works for up to three panes and that between-glass shades can only be placed between the inner two panes.  Is this still true?
- [ ] The equivalent layer window model supports many layers in any order, but the I/O Ref and Engineering Ref are silent about whether this can be used with WindowProperty:ShadingControl (at least I didn't find anything about that) and how it would be applied.

- ***addressed in issue #5603. (added notes in I/O and Eng. Ref documents).***

**Comment by Nigusse** [comment]
WindowProperty:ShadingControl is not supported in EquivalentLayer window model. But the WindowMaterial:Blind:EquivalentLayer blind object has its own slat angle control.

**Comment by mjwitte** [comment]
- [ ] Helpdesk ticket 1134, Engineering Reference section about "Hot Water Heat Recovery from Chillers" does not discuss chiller heat recovery and condenser water flow rates.  It appears from a quick inspection of the code for Chiller:Electric:EIR that both the heat recovery and condenser sides of the chiller request either zero flow or full flow. Is this true?  Should it always request full flow?  Maybe this is discussed elsewhere?

**Comment by mjwitte** [comment]
- [x] Helpdesk ticket 11345, Searching ExampleFiles.html for "residential" revealed several occurrences of the same typo: "residetial". This means the typo appears in the comments of these five example files:  AirflowNetwork_MultiZone_House.idf, AirflowNetwork_MultiZone_House_OvercoolDehumid.idf, AirflowNetwork_MultiZone_House_TwoSpeed.idf, AirflowNetwork_Simple_House.idf, and SingleFamilyHouse_TwoSpeed_ZoneAirBalance.idf

- ***addressed in #5603***

**Comment by mjwitte** [comment]
- People object Fraction Radiant is a required field but it has no default.  Should add a default.  0.3 ok?  idd and I/O Ref.
  - [x] IDD changes _Addressed in #5817_
  - [ ] ***Doc changes(I/O Reference)  addressed in #5603.***

- ***ASHRAE HOF 2017, Chapter 18, Table 1, recommends radiant fraction that range from 0.49 to 0.60 for low air velocity and from 0.19 to 0.35 for high air velocity depending on degree of activity.***

**Comment by mjwitte** [comment]
- [ ] The HAMT model should state somewhere that the outside surface relative humidity (RH) is always forces for 100% for surfaces with the Ground boundary condition. (From helpdesk ticket 11395).

- [x] ***addressed in issue #5603 added "Surfaces with Ground exterior boundary condition assumes saturated air ( 100% relative humidity) condition to calculate the exterior mass transfer coefficient, which is then used to model the mass transport through a ground contact surfaces.". This was added in engineering reference.***

**Comment by Myoldmopar** [comment]
@mjwitte Is this a place you _want_ small doc issues thrown in by other people?  Or is this your personal punchlist that you don't expect outside people to add onto?

**Comment by mjwitte** [comment]
@Myoldmopar Anyone is welcome to add to the list here.  When it starts to get long, then it's time to make a new one.  The concept here is to reduce effort in tracking and implementing a bunch of little doc changes - batch processing.

**Comment by Myoldmopar** [comment]
Great!
- [ ] This from @ebonnema, appears to be the IORef.

> Just found a very minor documentation thing, at the bottom of page 1292 the supply air fan operating mode schedule name should be numbered like the rest of the fields.

**Comment by eringold** [comment]
- [ ]  Update Coil:Cooling:Water default heat exchanger configuration per https://github.com/NREL/EnergyPlus/issues/5601
- [ ] Typo: https://github.com/NREL/EnergyPlus/blob/dacc4aba65b7b43bf253551b9028e55ded1445a8/doc/engineering-reference/src/on-site-generation/generators.tex#L3

- ***addressed in issue #5603 (changed the I/O reference to match the Idd.)***

**Comment by jasondegraw** [comment]
- [ ] The equations in the input/output reference for Curve:ExponentialDecay and Curve:ExponentialSkewNormal aren't rendering quite right. Both have problems with `exp`.

- ***addressed in issue #5603 (corrected equations)***

**Comment by mjwitte** [comment]
- [ ] The equation for Sky emissivity in the Auxiliary Programs doc has the incorrect sign (+/-) before the 0.0035.  This is how it should look (from v8.1 docs).

![image](https://cloud.githubusercontent.com/assets/4991075/16021838/6304c2c4-317a-11e6-85fb-1edc6914f9ac.png)

And this is the current (v8.5) incorrect equation:

![image](https://cloud.githubusercontent.com/assets/4991075/16021864/84dee0dc-317a-11e6-8528-001333b80ac5.png)

Error was introduced in v8.3

- ***addressed in issue #5603 (corrected the sign).***

**Comment by mjwitte** [comment]
- [ ] In the Engineering Reference, the equation for EIRfplr for Chiller:Electric:EIR is incorrect in v8.5 docs.  CapFT and EIRFT should be in the denominator.  Helpdesk ticket 11429.

**Note that this equation appears twice.**  Even in the earlier versions it was somewhat ambiguous.  Would be better as a stacked fraction.

v8.5
![erdoc1](https://cloud.githubusercontent.com/assets/4991075/16161931/b7638922-3495-11e6-803c-f280018c7674.png)

v8.4
![image](https://cloud.githubusercontent.com/assets/4991075/16161948/d5b63f14-3495-11e6-8c05-1897ee629347.png)

v8.3
![image](https://cloud.githubusercontent.com/assets/4991075/16161965/e0fd4b06-3495-11e6-809a-5df45e3d6f88.png)

- ***the engineering reference of V8.9 in develop looks correct. verified as part of #5603.***

**Comment by eringold** [comment]
- [x] I/O Ref HAMT object outputs appearing where they should not. They have replaced the missing outputs section (and possibly some inputs) for Construction:InternalSource [here](https://github.com/NREL/EnergyPlus/blob/080219f60449af4e66e559831a17688986f2a5fa/doc/input-output-reference/src/overview/group-surface-construction-elements.tex#L3813-L3896). They also show up in the 'Constructions' section [here](https://github.com/NREL/EnergyPlus/blob/080219f60449af4e66e559831a17688986f2a5fa/doc/input-output-reference/src/overview/group-surface-construction-elements.tex#L3537-L3619). Seeing this as far back as the v8.0 docs. 
- [x] Add output variables for Construction:InternalSource (see above). 

_Both of these are addressed in #5810._

**Comment by mjwitte** [comment]
- [x] In IDD, Sizing:System, field A7, \field Heating Supply Air Flow Rate Method, key choice "FlowPerCoolingCapacity" should be "FlowPerHeatingCapacity".  From helpdesk ticket 11502.

_Addressed in #5817_

**Comment by mjwitte** [comment]
- [ ] I/O Ref, the figures for AirTerminal:SingleDuct:Mixer are missing lines.  [image275.png](https://github.com/NREL/EnergyPlus/blob/c87e61b44bce627bc0fac6f0574d9b018015a3be/doc/input-output-reference/media/image275.png) and  [image276.png](https://github.com/NREL/EnergyPlus/blob/c87e61b44bce627bc0fac6f0574d9b018015a3be/doc/input-output-reference/media/image276.png)

- ***addressed in issue #5603 (replaced it with modified image)***

**Comment by Nigusse** [comment]
-  [ ] I see figures position floating in IORef for "GroundHeatExchanger:Surface" object as well. image205.png and image206.png Here, and above, arrowheads show, but the lines to the arrowheads are missing.

- ***addressed in issue #5603 (replaced with modified images).***

**Comment by mjwitte** [comment]
- [ ] Fix #5793

**Comment by Nigusse** [comment]
- [ ] I/O Ref, in section 1.47.12 AvailabilityManager:OptimumStart the description for the input field "Control Algorithm" says, "The AdaptiveASHRAE algorithm has not been implemented yet." But the IDD for this input field says, "default value for Input field "Control Algorithm" is AdaptiveASHRAE. The I/O Ref is out of date.  The develop version of latex document has the same issue.

- ***addressed in issue #5603 ( corrected it with AdaptiveASHRAE algorithm as default)***

**Comment by rraustad** [comment]
- [ ] EnergyPlus_Support question:
  
  The input output reference for WindowMaterial:Glazing under 'Field: Visible Transmittance at Normal Incidence' states:
  
  > "For uncoated glass, when alternative optical properties are available—such as thickness, visible index of refraction, and visible extinction coefficient—they can be converted to equivalent visible transmittance and reflectance values using the equations given in “Conversion from Alternative Specification of Glass Optical Properties.”

Reference to equations should be: "Glass Optical Properties Conversion" (change 2 places in IO Ref). Equations shown In Eng. Ref. pg 273.

- ***addressed in issue #5603 (edited as suggested)***

**Comment by EnergyArchmage** [comment]
In the Engineering Reference, section "Loop, Equipment Sizing and Other Design Data", "Compent Sizing" 
- The Boiler Sizing heading level is suppressed and its content lies under Electric Chiller Sizing
- The chiller and boiler sizing calculations are missing a term for the component level sizing factor.  Plant sizing factors were added to many components but the sizing calculation documentation doesn't appear to reflect that.  Should check for other places it may be missing. 

- ***these issues appear to be already resolved in develop V8.9***

**Comment by shorowit** [comment]
This is observed in the E+ 8.5 Input/Output Reference documentation:
- [ ] **Field: Stack Coefficient** for the **ZoneInfiltration:EffectiveLeakageArea** object references a table of stack coefficient values but the table is missing. Only the table with shelter classes is available. Field: Wind Coefficient correctly has both tables.
- [ ] **Field: Stack Coefficient** for the **ZoneInfiltration:FlowCoefficient** object references a table of stack coefficient values but the table is missing. Only the table with shelter classes is available. Field: Shelter Factor correctly has both tables.
- [ ] **Field: Wind Coefficient** for the **ZoneInfiltration:FlowCoefficient** object references a table of stack coefficient values but the table is missing. Only the table with shelter classes is available. Field: Shelter Factor correctly has both tables.

- ***these issues appear to be already resolved in develop V8.9***

**Comment by EnergyArchmage** [comment]
in OutputDetailsAndExamples, section "Output Files", "eplustbl.<ext>"  There a great many sample tables where content is completely messed up and just keeps repeating a sample that is supposed to be from the Construction Cost Estimate Summary. This garbage goes from page 195 to page 291

**Comment by mjwitte** [comment]
@EnergyArchmage Is that in the latest docs on Develop? [current ones here](http://energyplus.s3-website-us-east-1.amazonaws.com/assets/2016-08-24-EnergyPlus-a17aa64355-x86_64-gcc-4.8/).

**Comment by EnergyArchmage** [comment]
oh, no I was looking at 8.5 release docs, I guess the table output details already got fixed.

**Comment by mjwitte** [comment]
- [ ] Change all energyplus.gov references to energyplus.net and check other link descriptions.  Quick search finds 20 occurrences across all the doc source files, some with longer links that will need updating, and some with textual references to further links that probably need updating.

**Comment by MatthewSteen** [comment]
- [ ] Daylighting:Controls [Number of Stepped Control Steps](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-daylighting.tex#L78) field is missing a note about the default.

N17, \field Number of Stepped Control Steps
      \note for Lighting Control Type=2, this field cannot be zero.
      \type integer
      \default 1

- ***addressed in issue #5603 (added a note, adopted from I/O ref).***

**Comment by mjwitte** [comment]
- [ ] I/O Ref descriptions for VRF Heat Pump Heating Electric Power (and Consumption) incorrectly state that crankcase heater and/or defrost are included in these amounts.  The power for those are reported separately.  VRF Heat Pump Heating Electric Power only includes the compressor and outdoor fan energy.  From helpdesk ticket 12275.

- ***addressed in issue #5603 (modified as suggested and also verified against current code).***

**Comment by Nigusse** [comment]
Any one working on this issue?

**Comment by Myoldmopar** [comment]
Closed via #6463
