### ISSUE TITLE
Sizing Consolidation - Next Steps

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6172]
Sizing issues highlight several facts on coil sizing:

 - [ ] HW and CW coils use different initialization temperatures for Cp and Rho. Use HWInitConvTemp and CWInitConvTemp consistently for each coil type.
 - [ ] sizing for rated air flow and capacity need to be synchronized.
 - [ ] Recent issues highlight a flaw in sizing where FinalZoneSizing.DesHeatCoilInTemp is not always correct. ReportSizingManager should always calculate coil entering air temp based on OA fraction. Likely same issue for cooling mode.
 - [ ] The use of SystemAirFlow, HeatingAirFlow and CoolingAirFlow flags set by parent objects has gotten a little out of hand. The SystemAirFlow flag was originally intended for fan sizing, at max of cooling and heating flow rates. The Heating and Cooling AirFlow flags were meant for the respective coils where each could be sized using a different air flow rate (if the SystemAirFlow check is present in coil cases then the coils will size the same as the fan instead of independently - if coils should size the same is the parent responsibility). In ReportSizingManager, the only occurrence of SystemAirFlow should be for fans. Also, for coil sizing the use of HeatingAirFlow for a cooling coil should not be present (e.g., CoolingCapacitySizing should not include the HeatingAirFlow flag or if they do remain they have corresponding priority?).
 - [ ] All zone equipment need to set ZoneEqSizing data at the end of the sizing routine.
      - [x] fan coil
      - [x] unit ventilator
      - [x] unit heater
      - [ ] PT Unit
      - [ ] Window AC
      - [ ] Others ?

 - [ ] All zone equipment need to set HeatingAirFlow and/or CoolingAirFlow flags and associated HeatingAirVolFlow and CoolingAirVolFlow magnitude data so coils size correctly. The same is true for parent OA flow rate using ZoneEqSizing( CurZoneEqNum ).OAVolFlow.
 - [ ] Some ReportSizingManager cases don't make sense, for example HeatingCapacitySizing for zone equipment has:

    if ( ZoneEqSizing(CurZoneEqNum).HeatingCapacity ) {, then 
    } else if ( DataCoolCoilCap > 0.0 && DataFlowUsedForSizing > 0.0 ) {, then
    } else if ( FinalZoneSizing( CurZoneEqNum ).DesHeatMassFlow >= SmallMassFlow ) {, and finally
    } else {
            NominalCapacityDes = 0.0;

    so if other higher priority sizing techniques are not used we can't size the coil unless the zone heat mass flow rate > 0 ? What if this coil is in a parent object that does have air flow rate > 0, the heating coil should still size. This logic puts the responsibility on the parent and then the "else" may become irrelevant.

 - [ ] Over time many new variables have been created to fix specific sizing issues. This variable creep has led to non-uniform sizing for specific coil configurations (e.g., TUs, fan coils, PIUs, etc.). Special care should be used to remove these if possible.

 - [ ] ReportSizingManager is duplicative in that there is both zone equipment and air loop equipment sections. It would be very good to figure out a way to consolidate this into one generic code base. For example, if the FinalZoneSizing and FinalSysSizing arrays had the same variables, then a pointer could choose which is used and then this function would be half the size. Of course this means that coil sizing of zone vs air loop coils would first need to be unified.

 - [ ] A rule set needs to be created describing the valid use of the ZoneEqSizing data. All developers and reviewers must be aware of these rules.

    There are 3 flags used to size air flow:

        ZoneEqSizing( CurZoneEqNum ).SystemAirFlow
        ZoneEqSizing( CurZoneEqNum ).HeatingAirFlow
        ZoneEqSizing( CurZoneEqNum ).CoolingAirFlow

    These flags have corresponding magnitude variables:

        ZoneEqSizing( CurZoneEqNum ).AirVolFlow
        ZoneEqSizing( CurZoneEqNum ).HeatingAirVolFlow
        ZoneEqSizing( CurZoneEqNum ).CoolingAirVolFlow

    These flags and magnitudes need to be set in unison. With the understanding of what each is used for. SystemAirFlow for fans, HeatingAirFlow for heating coils, and CoolingAirFlow for cooling coils. Sizing routines needs to reflect these rules.

Then there are capacity flags and magnitudes used to size coils. These also need to be used appropriately.

        ZoneEqSizing( CurZoneEqNum ).CoolingCapacity
        ZoneEqSizing ( CurZoneEqNum ).DesCoolingLoad
        ZoneEqSizing( CurZoneEqNum ).HeatingCapacity
        ZoneEqSizing ( CurZoneEqNum ).DesHeatingLoad

 - [ ] There is standard practice that coils need to be able to meet a minimum supply air temperature to avoid call backs. Recent changes have addressed that need (i.e., calculation of actual inlet air temp to size the coil - #6028, #6079). This methodology needs to be scrutinized and defined to a point where manufacturers agree, support, contribute, etc. with E+ methods.

 - [x] issue #6006 corrected a problem with heating coil not sizing when zone heating load = 0. This fix was ported to cooling coils but not completely.  Line 2782 of ZoneEquipmentManager does not include a corresponding line like this. Also, the HumRat equivalent can't be mined from the Tstat, so how do we set those variables when loads <= 0 ?

        FinalZoneSizing( CtrlZoneNum ).OutTempAtHeatPeak = *std::min_element( ZoneSizing( DDNumF, CtrlZoneNum ).HeatOutTempSeq.begin(), ZoneSizing( DDNumF, CtrlZoneNum ).HeatOutTempSeq.end() );

 - [x] Multiple places in ReportSizingManager use similar lines of code. How to consolidate to less maintenance intensive code? Function calls? Do this once at the top of function and make OAFrac available to all? See issue #6712.

        if ( ZoneEqSizing( CurZoneEqNum ).SystemAirFlow ) {  << -- these to be removed as necessary
            DesMassFlow = ZoneEqSizing( CurZoneEqNum ).AirVolFlow * StdRhoAir;
        } else if ( ZoneEqSizing( CurZoneEqNum ).HeatingAirFlow ) {
            DesMassFlow = ZoneEqSizing( CurZoneEqNum ).HeatingAirVolFlow * StdRhoAir;
        } else {
            DesMassFlow = FinalZoneSizing( CurZoneEqNum ).DesHeatMassFlow;
        }
        if ( DesMassFlow > 0.0 ) {
            OutAirFrac = min( StdRhoAir * ZoneEqSizing( CurZoneEqNum ).OAVolFlow / DesMassFlow, 1.0 );
        } else {
            OutAirFrac = 0.0;
        }

 - [x] issue #6712 corrects zone coil sizing when AT SingleDuct Mixers are used. This effort uses new functions used in sizing.

Issue overview
--------------
Please change this line to a description of the defect, with useful supporting information including how the issue was found, conditions that trigger this defect, workarounds for users of the current version, and a clear description of how to validate that a fix is complete for this defect.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
@mjwitte @Myoldmopar @EnergyArchmage tagging you all on this given it's importance.

**Comment by rraustad** [comment]
Please update these as needed,

**Comment by rraustad** [comment]
Here's just one example of things that will need correction.

A fan coil (from FanCoilAutoSizeScalableSizing) has a cooling and heating coil. The user enters a scalable sizing object and enters a flow rate for both coils. Given it's a fan coil. one would expect that the flow rate would be the max of these inputs.  Instead, the first input is used and the second input for heating flow rate is ignored.

    ZoneHVAC:FourPipeFanCoil,
      Zone1FanCoil,              !- Name
      autosize,                       !- Maximum Supply Air Flow Rate {m3/s}
      Fan:ConstantVolume,   !- Supply Air Fan Object Type
      Coil:Cooling:Water,       !- Cooling Coil Object Type
      Coil:Heating:Water,       !- Heating Coil Object Type
      FanCoilDesignSpec1;    !- Design Specification ZoneHVAC Sizing Object Name

    DesignSpecification:ZoneHVAC:Sizing,
      FanCoilDesignSpec1,    !- Name
      SupplyAirFlowRate,       !- Cooling Supply Air Flow Rate Method
      0.01,                              !- Cooling Supply Air Flow Rate {m3/s}
      SupplyAirFlowRate,       !- No Load Supply Air Flow Rate Method
      0.01,                              !- No Load Supply Air Flow Rate {m3/s}
      SupplyAirFlowRate,       !- Heating Supply Air Flow Rate Method
      0.2,                                !- Heating Supply Air Flow Rate {m3/s}

The result shows design size at 0.01 m3/s when the values specified here are 0.01 and 0.2. This is the parent (i.e., no other object set a flow rate for this object). I think the answer should be 0.2.

     Component Sizing Information, ZoneHVAC:FourPipeFanCoil, ZONE1FANCOIL, Design Size Maximum Supply Air Flow Rate [m3/s], 1.00000E-002
     Component Sizing Information, ZoneHVAC:FourPipeFanCoil, ZONE1FANCOIL, User-Specified Maximum Supply Air Flow Rate [m3/s], 1.00000E-002
     Component Sizing Information, Fan:ConstantVolume, ZONE1FANCOILFAN, Design Size Maximum Flow Rate [m3/s], 1.00000E-002
     Component Sizing Information, Coil:Cooling:Water, ZONE1FANCOILCOOLINGCOIL, Design Size Design Air Flow Rate [m3/s], 1.00000E-002

  Coil:Cooling:Water,
    Zone1FanCoilCoolingCoil, !- Name
    autosize,                !- Design Air Flow Rate {m3/s}

The user autosized the cooling coil air flow rate, still not sure what this should report. I would think the design size would be 0.42 and the user specified would be 0.01.

     Component Sizing Information, Coil:Cooling:Water, ZONE1FANCOILCOOLINGCOIL, Design Size Design Air Flow Rate [m3/s], 1.00000E-002
     Component Sizing Information, Coil:Cooling:Water, ZONE1FANCOILCOOLINGCOIL, User-Specified Design Air Flow Rate [m3/s], 0.42193

The heating coil does not show an air flow rate but I did notice that the heating capacity does not change with change in scalable heating air flow input but the UA does. That seems correct. (this is off topic but I think the UA calculated for water coils assumes a constant air flow rate, i.e., air flow rate used during simulation cannot be different from sizing)

     Component Sizing Information, Coil:Heating:Water, ZONE1FANCOILHEATINGCOIL, Design Size Design Coil Load [W], 5929.44720
     Component Sizing Information, Coil:Heating:Water, ZONE1FANCOILHEATINGCOIL, Design Size U-Factor Times Area Value [W/K], 154.22361

**Comment by rraustad** [comment]
Can someone help me with the last bullet where redundant lines of code could be consolidated into something? Not sure what that might be, a function call, move to top of routine and always calculate, do during sizing if possible?, etc. Asking for suggestions.

**Comment by mjwitte** [comment]
@rraustad Brainstorming here . . .
As you suggested, some small functions for specific calculations like OAfrac, coil inlet temp, etc. are one possibility.  Ultimately these may be quite simple and self-contained - calc OA frac, calc coil inlet temp, or calc scalable airflow.  A lot of the duplicate-looking code comes from the same basic equation grabbing different temperatures, for example, depending on the location of the coil:
```
CoilInTemp = ( 1.0 - OutAirFrac ) * FinalZoneSizing( CurZoneEqNum ).ZoneTempAtHeatPeak + OutAirFrac * FinalZoneSizing( CurZoneEqNum ).OutTempAtHeatPeak;
CoilInTemp = OutAirFrac * FinalSysSizing ( CurSysNum ).PrecoolTemp + ( 1.0 - OutAirFrac ) * FinalSysSizing ( CurSysNum ).RetTempAtCoolPeak;
CoilInTemp = OutAirFrac * FinalSysSizing( CurSysNum ).PreheatTemp + ( 1.0 - OutAirFrac ) * FinalSysSizing( CurSysNum ).HeatRetTemp;
CoilInTemp = OutAirFrac * FinalSysSizing( CurSysNum ).HeatOutTemp + ( 1.0 - OutAirFrac ) * FinalSysSizing( CurSysNum ).HeatRetTemp;
```
So, one approach would be to change these to
```
CoilInTemp = CalcCoilInTemp( OutAirFrac, FinalZoneSizing( CurZoneEqNum ).ZoneTempAtHeatPeak, FinalZoneSizing( CurZoneEqNum ).OutTempAtHeatPeak )
```

But it would also be nice to collapse all of the logic leading into these similar sections of code.  Step back and think the various use cases and eliminate the equipment dependencies here.  As a do-no-harm first step - maybe keep all the current logic and make small task functions that do the calculations.  A next step might be to break up RequestSizing into separate calls and move towards eliminating the DataSizing:Data* flags.  For example, instead of setting flags and invoking RequestSizing to sort it out, perhaps call RequestSizingForDXHeatingCoil instead.  This means changing code in the component sizing routines.  And there's more than one way to slice this.

Just some thoughts to get started.

**Comment by EnergyArchmage** [comment]
I think that a thorough refactor of RequestSizing is high priority.  Although it is extremely challenging, my view is that working on a clever new overall design would be more productive than making incremental improvements to current code.   I would be happy to help work on a new design but it would be a sizable project and need funding.   

Here are some of the characteristics I would imagine the new design having:

- Scope of redesign remains similar to what RequestSizing does now. Basically connect the existing zone and system sizing data structures to the component model's sizing routines.  Continue to try to move code out of component sizing routines and into central device sizing objects.
- new OO device sizing top level (virtual) object, eg. DeviceSizeObj
- new OO coil sizing objects, e.g. CoilSizeObj, inherits from top level DeviceSizeObj, perhaps third level classes for different coil types, UA , eg. HeatUACoilSizeObj, CoolDetailedCWCoilSizeObj, 
- new OO fan sizing object inherits from top level, e.g. FanSizeObj
- component models would instantiate device sizing objects as needed, The content now in DataSizing:Data* flags is moved into new device sizing objects and instead of calling into Request Sizing pass the component models would just call methods on the device sizing object.
- Request Sizing gets broken up into dozens of small methods that become parts of the device sizing objects.  Some are common to all and contained in the top level object, some methods are unique to different devices and contained in the lower level object(s).

**Comment by rraustad** [comment]
I don't disagree and this would be well past my ability. 

I do think that there have been several changes to sizing methodology where we need to understand what those changes represent. For example, calculating a coil inlet temp based on OAFrac and ZoneTempAtHeatPeak instead of using the FinalZoneSizing.DesHeatCoilInTemp. This is important when a parent operates at a flow rate different than the zone design air flow rate.

If there were to be a refactor it would need to be done in a way that minimized diff's so we knew we didn't change anything. Move to OO and test, then move on to another item and test, etc.
