### ISSUE TITLE
Additional Terminal Unit Sizing Issues

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6481]
Issue overview
--------------
Followup terminal unit sizing issue from #6338.
- [x] In `SimAirServingZones::UpdateSysSizing, DesHeatCoilInTempTU` is set for heating zones only using `GetHeatingSATempForSizing` (similar for humrat) [here](https://github.com/NREL/EnergyPlus/blob/c0223f6ed62d7242a3a84cd568a402706033ba6a/src/EnergyPlus/SimAirServingZones.cc#L6617-L6634). In #6338, for consistency with other blocks in `UpdateSysSizing`, I added a loop here over cooled zones for completeness, show [here](https://github.com/NREL/EnergyPlus/blob/a51f7d499d610d3e9efc45cb318d38e58e280143/src/EnergyPlus/SimAirServingZones.cc#L6558-L6564). But that caused large changes in reheat coil sizing across many files - maybe these are OK, but too much to review at this point, so the new block over cooled zones was removed.

- [x] Review diffs from system sizing refactor #6372 and fix here if needed.

- [x] Review diffs from new coil sizing report #6454 and possibly reinstate or modify the lines that were reverted [here](https://github.com/NREL/EnergyPlus/pull/6454/commits/57a0055f560e70dbde62339230f7acf3c0907a93) which, BTW, were suspected of causing diffs but nothing changed after this commit.  Also, see various comments from @rraustad in #6454 .
@EnergyArchmage addressed this in 75fdccb0dfad2dcea8a5cf9e58e6ccf2f1a9cd8e

- [x] Try to resolve performance hit introduced in #6372 Here are the timing results from #6372 and the prior merge which was #6388 
[PR6372 timing results.pdf](https://github.com/NREL/EnergyPlus/files/1741516/PR6372.timing.results.pdf)
[PR6388 timing results.pdf](https://github.com/NREL/EnergyPlus/files/1741520/PR6388.timing.results.pdf)
Addressed in #6489 

- [x] PR6481 initially caused a bunch of new errr messages about table units conversions
```
  ** Warning ** Unable to find a unit conversion from Coil Entering Air Humidity Ratio at Ideal Loads Peak [kg-H2O/kg-DryAir] into IP units
+   **   ~~~   ** Applying default conversion factor of 1.0
+   ** Warning ** Unable to find a unit conversion from Outdoor Air Humidity Ratio at Ideal Loads Peak [kg-H2O/kg-DryAir] into IP units
+   **   ~~~   ** Applying default conversion factor of 1.0
+   ** Warning ** Unable to find a unit conversion from Zone Air Humidity Ratio at Ideal Loads Peak [kg-H2O/kg-DryAir] into IP units
+   **   ~~~   ** Applying default conversion factor of 1.0
+   ** Warning ** Unable to find a unit conversion from Plant Design Fluid Temperature Difference [Delta C] into IP units
```
These have been addressed in https://github.com/NREL/EnergyPlus/pull/6454/commits/bb00e38352c1e0d7fab049a1db3e2806932a5e84 by switching to existing units strings, e.g. KGWATER/KGDRYAIR, but we might prefer to add some new units strings instead.

- [x] Other errors from #6454 
```
5ZoneDDCycOnAny and many others
+   ** Severe  ** MyPlantSizingIndex: Could not find HOT WATER LOOP in Sizing:Plant objects.
+   **   ~~~   ** ...reference Component Type="hot water coil", Name="SPACE1-1 ZONE COIL".

UnitarySystem_WaterCoils_wMultiSpeedFan
+   ** Warning ** In calculating the design coil UA for Coil:Cooling:Water CW COOLING COIL
+   **   ~~~   ** no apparatus dew-point can be found for the initial entering and leaving conditions;
+   **   ~~~   ** the coil outlet design conditions will be changed to correct the problem.

VSHeatPumpWaterHeater
+   ** Warning ** WetBulb not converged after 101 iterations(PsyTwbFnTdbWPb)
+   **   ~~~   **  Routine=ReportCoilSelection::doFinalProcessingOfCoilData,

```

- [x] Coil locations are not being found now

- [x] Need unit tests for both Std 62 and coil sizing report.
### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed now that #6338 and #6500 are both in.
