### ISSUE TITLE
RunPeriod Merge Followup

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6926]
Issue overview
--------------
Remaining issues from #6478 RunPeriod changes.
- [x] No. 1. Change in table output average occupancy (e.g. PlateHeatExchanger.idf) *Addressed in #6972*

- [x] No. 5. Schedule:File - multi-year leap year behavior question:
Searching the I/O Ref for "leap", found this under Schedule:File. What happens if the simulation is multi-year and include a leap year?

> Note if the simulation does not have a leap year specified but the schedule file
contains 8784 hours of data, the first 8760 hours of data will be used. The schedule manager will
not know to skip the 24 hours representing February 29.

- [x] No. 6. Almost there - Now getting full years, but there's one extra day. Looks like any simulation longer than a year models one extra day. 
e.g. 5ZoneAirCooled-NoDay-2016-2020-FullYears.idf reports the correct start and end dates, but the number of days is one too many (should be 1825)
WeatherFileRunPeriod,01/01/2016,12/31/2020,Friday,1826
and the output includes an extra day for 01/01/2021.

- [x] No. 11 Moved to #6937

- [x] No. 12 As noted [here](https://github.com/NREL/EnergyPlus/pull/6478/commits/7042b1ef3abd464fc2328959e0ff03e40324a871#r212616314), for test file PipingSystem_Underground_TwoPipe_FD_GroundTemps.idf, `NumOfDayInEnvrn` = 366 [here]( https://github.com/NREL/EnergyPlus/blob/c4de98c52a99dccf8ef85e34b9a50a5fbda0f0aa/src/EnergyPlus/GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel.cc#L263) in GroundTemperatureModeling/FiniteDifferenceGroundTemperatureModel. It's a simple runperiod and if you run the weather file simulation, you get 365 days, so why does it think it's 366 here?

- [x] No. 13 Some of the eio diffs are for runs which use SizingPeriod:WeatherFileConditionType , e.g. DDAutoSize.idf. These are showing year=0, probably shouldn't include a year for these types of environments (same as for SizingPeriod:DesignDay). Same thing happens for SizingPeriod:WeatherFileDays (MultiStory.idf) *Addressed in #6972*
```
-Environment,EXTREME SUMMER WEATHER PERIOD FOR DESIGN,User Selected WeatherFile Typical/Extreme Period (Design)=SummerExtreme,07/13,07/19,SummerDesignDay,7,Use RunPeriod Specified Day,No,No,No,No,No
+Environment,EXTREME SUMMER WEATHER PERIOD FOR DESIGN,User Selected WeatherFile Typical/Extreme Period (Design)=SummerExtreme,07/13/0,07/19/0,SummerDesignDay,7,Use RunPeriod Specified Day,No,No,No,No,No
-Environment,WEATHER FILE SIZING PERIOD,User Selected WeatherFile RunPeriod (Design),07/18,07/25,SummerDesignDay,8,Use RunPeriod Specified Day,No,No,No,No,No
+Environment,WEATHER FILE SIZING PERIOD,User Selected WeatherFile RunPeriod (Design),07/18/0,07/25/0,SummerDesignDay,8,Use RunPeriod Specified Day,No,No,No,No,No
```

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.0.0-https://github.com/NREL/EnergyPlus/pull/6478/commits/e321ae66ce0390cdd4aa1e00922cbac996543c17

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jasondegraw** [comment]
@mjwitte For no. 11, I think that was because RunPeriods didn't have to have names before, so there probably wasn't a better way to identify which RunPeriod was generating a error/warning. Are RunPeriods required to have a name now?

**Comment by mjwitte** [comment]
Names aren't required in idf, but the new input processor adds one if blank so they don't overwrite in the json data.

**Comment by jasondegraw** [comment]
@mjwitte What's the use case for not requiring the run periods to have names? It's going to be hard for users to track errors back to the input object without a name. I guess we could report the name alongside the number, but it seems to me that having a name would be better (which would need to wait until next release).

**Comment by mjwitte** [comment]
It's changed over time. Originally there wasn't a name field. I don't recall why it wasn't required at the time it was added. I wouldn't object to making it required in thenext release. I'm pretty sure the names added by IP are Runperiod1 etc. We can defer changing the warnings if you want.

**Comment by jasondegraw** [comment]
@mjwitte I'd prefer to push that for now, we should require names in the future. No. 6 is only happening for end years that are leap years, otherwise it's good. I'll move 11 to a separate issue.

**Comment by jasondegraw** [comment]
@mjwitte I've tracked down No. 1 to the use of `USEWEATHERFILE` in the run period. Different starting weekdays are being used for the run periods (Sunday instead of Wednesday and Tuesday). The transition program should be OK for our weather files, as we're blanking that and letting E+ set the date properly (the default year starts with a Sunday, as do all of our EPWs). I transitioned the example files by hand/script, and at the time I was putting in Sunday instead of a blank. I'll go back through and correct that. That leaves Nos 5 and 13.

**Comment by mjwitte** [comment]
As long as there's an explanation, I don't know if it really matters what day those files start on. It's up to you if you want to change them, or just leave them as-is.

**Comment by jasondegraw** [comment]
@mjwitte I'll try to fix it, I'd rather have the example files look like they were transitioned with the program (even if that's not what happened). I haven't been able to reproduce No. 13, any suggestions on how to do that?

**Comment by mjwitte** [comment]
What happens for `SizingPeriod:DesignDay`? Is there a year associated with the simulation for that? I believe those still report without a year. I think the other types of `SizingPeriod` use the specified day type for the entire period whether it's a single extreme day or a range of dates. Assuming these are simulating correctly, the easiest fix is to trap these types of environments when reporting to the eio and report without the year, same as for design days.

**Comment by jasondegraw** [comment]
I'll take a look. I've gotten some other reports about weird years, but I have yet to generate any myself.

**Comment by jasondegraw** [comment]
@mjwitte So I think I've addressed No. 1 and No. 13 now, the year output is suppressed for everything but environments that claim to be of  `ksRunPeriodWeather` kind.

**Comment by mjwitte** [comment]
Are you planning to push up these changes?

**Comment by jasondegraw** [comment]
Yes, I've got a couple things to address still over on a branch. Will create a PR in a few minutes.

**Comment by jasondegraw** [comment]
@mjwitte It appears that the documentation is a little confusing and possibly wrong w.r.t. Schedule:File and leap years, but after fixing an error I'm getting successful simulations including leap years. If I understand the code in ScheduleManager.cc, it's duplicating Feb28 into Feb29 for 8760 hours of data, and reading in that day when are 8784 hours of data. So it sure seems like it does know how to skip that day, so maybe that needs to get clarified.

**Comment by Myoldmopar** [comment]
Closed via #6972
