### ISSUE TITLE
Documentation Issues - 2018b

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7026]
Issue overview
--------------
A collection of small documentation issues. See checkboxed comments below.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
- [x] I/O Ref documentation for these output variables should appear under `ZoneHVAC:AirDistributionUnit` and nowhere else:
```
Output:Variable,*,Zone Air Terminal Sensible Heating Energy,hourly; !- HVAC Sum [J]
Output:Variable,*,Zone Air Terminal Sensible Cooling Energy,hourly; !- HVAC Sum [J]
Output:Variable,*,Zone Air Terminal Sensible Heating Rate,hourly; !- HVAC Sum [W]
Output:Variable,*,Zone Air Terminal Sensible Cooling Rate,hourly; !- HVAC Sum [W]
```
Currently these are repeated under a few of the specific air terminal units, but not all of them. Since these are produced with the ATU name as the key value, they should be documented there and removed elsewhere.  The one exception is `AirTerminal:SingleDuct:Uncontrolled` which does produce it's own output variables, but that's going away soon.
Also, some of the air terminals have their own specific output variables, such as Zone Air Terminal VAV Damper Position, so don't delete those definitions.

*EnergyPlus v9.0.1, unmethours [35070](https://unmethours.com/question/35070/how-e-calculate-the-ventilation-loads-and-what-is-the-output/).*

**Comment by mjwitte** [comment]
- [x] EMS Application Guide, description of Plant Supervisory Control, Plant Component \*, On/Off Supervisory is incorrect. The current description says that zero means the component and its branch will be off (this is correct), and it says any other value means operate normally (this is *not* correct).  Here is how it's used in the [code](https://github.com/NREL/EnergyPlus/blob/c1a8cbbf47edf480e3c9e680a32d310591a11b3c/src/EnergyPlus/PlantCondLoopOperation.cc#L3426-L3437):
` this_comp.MyLoad = min(this_comp.MaxLoad, (this_comp.MaxLoad * this_comp.EMSLoadOverrideValue));`

So, the last sentence of the description should be changed:
Setting the value of this actuator to ~any other value directs this component and any other component on the same branch to run normally based on other controls.~ *any value <=1.0 sets the current load for this component to the actuator value times the component maximum operating capacity which is the nominal capacity multiplied by the maximum part load ratio.*

- [x] In the edd, this actuator is shown with units of [W], it should be [fraction], [code is here](https://github.com/NREL/EnergyPlus/blob/c1a8cbbf47edf480e3c9e680a32d310591a11b3c/src/EnergyPlus/PlantCondLoopOperation.cc#L3339-L3344).

*EnergyPlus v9.0.1, unmethours [35215](https://unmethours.com/question/35215/control-current-heating-load-of-a-boiler-for-every-timestep/).*

**Comment by mjwitte** [comment]
- [x] Engineering Reference, "Tables based on a single independent variable", in the sample idf object for `Table:OneIndependentVariable`, the field for "Maximum Table Output" should be 125, not 64.

*EnergyPlus 9.0.1, Helpdesk 13095.*

UPDATE: Fixed by #6749, but I cleaned up a stray ```Table:OneIndependentVariable``` reference.

**Comment by mjwitte** [comment]
- [x] Engineering Ref, v9.0.1 p. 160, the section headings for "Ground Heat Transfer Calculations using Site:GroundDomain:Slab" and Basement fall off the edge of the page.

![image](https://user-images.githubusercontent.com/4991075/48644807-618a5280-e9a9-11e8-8d0c-187cbac255d3.png)

**Comment by mjwitte** [comment]
- [x] Reading the I/O ref guide, it isn't clear what the Site:GroundDomain:Basement Aspect Ratio means. The help says: 

"Numeric field used to define the height to width ratio of the slab."

Whereas for the equivalent basement object the help is clearer:

"Numeric field, which is the ratio of basement length to width, used to determine the aspect
ratio of the basement. This field along with the total basement floor area, which is taken as the
combination of all surfaces connected to the floor OtherSideConditionsModel, are used to determine
the size and shape of the basement domain. Aspect ratios and the inverse of aspect ratios should
produce identical results. i.e. AR = 2 equals AR = 0.5. This field has units of meters/meters."

Should we assume that the aspect ratio for the basement object is actually the ratio of length to width, not slab height (depth) to width?
@mitchute ?

Same is true in the Engineering Ref, for GroundDomain:Slab, the aspect ratio isn't even mentioned.

*EnergyPlus v9.0.1, helpdesk ticket 13113.*

**Comment by mitchute** [comment]
Yes, on a plan view, this is the length to width ratio.

**Comment by jmarrec** [comment]
* [x] Auxiliary Programs for stuff like ParametricSpreadsheets references local folders that don't exist anymore and the energyplus.net/extras page. Related to #5423 

![image](https://user-images.githubusercontent.com/5479063/48775075-47fc4a00-eccc-11e8-876a-d18251663bf4.png)

***UPDATE: References to "energyplus.net" in docs. Will verify whether each is valid.***

* [x] ./interface-developer/src/licensing.tex (valid)
* [x] ./input-output-reference/src/overview/group-location-climate-weather-file-access.tex (corrected)
* [x] ./auxiliary-programs/src/doe2translator.tex (deleted)
* [x] ./auxiliary-programs/src/blasttranslator.tex (deleted)
* [x] ./auxiliary-programs/src/parametric-spreadsheets.tex (moved to #7739 )
* [x] ./auxiliary-programs/src/weather-converter-program/web-resources.tex (valid)
* [x] ./auxiliary-programs/src/weather-converter-program/weather-data-availability.tex (valid)
* [x] ./getting-started/src/energyplus-overview/energyplus-documentation-library.tex (corrected)
* [x] ./getting-started/src/other-useful-programs-information/datafiles.tex (valid)
* [x] ./essentials/essentials.tex (valid)

@Myoldmopar @mjwitte Do we remove all references to DOE2Translator, BlastTranslator, and Parametric Spreadsheets?

**Comment by jmarrec** [comment]
* [x] I/O Documentation for Cooling Towers is outdated and doesn't match E+ IDD. Eg: `CoolingTower:SingleSpeed` doesn't mention the "Design Approach Temperature", "Design Range Temperature", etc (Also typo: "Regine" instead of "Regime). Same for TwoSpeed at least

**Comment by MatthewSteen** [comment]
~~I/O for `Boiler:HotWater` missing the field `Design Water Outlet Temperature` [here](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-plant-equipment.tex#L3947) before the `Design Water Flow Rate field`.~~

**Comment by Nigusse** [comment]
@MatthewSteen the field "Design Water Outlet Temperature" has been removed.

**Comment by MatthewSteen** [comment]
@Nigusse my mistake. I noticed it in an OpenStudio model (2.7.0 with EP 9.0), but was looking at the 8.9 IDF Editor.

**Comment by mjwitte** [comment]
- [x] Engineering Reference, "Photovoltaic Thermal Flat-Plate Solar Collectors", this sentence:

> EnergyPlus currently has one simple model based on user-defined efficiencies but a more detailed model based on first-principles and a detailed, layer-by-layer description is under development.

Should be changed to:

> EnergyPlus currently has one simple model based on user-defined efficiencies. ~but a more detailed model based on first-principles and a detailed, layer-by-layer description is under development.~
.

**Comment by JasonGlazer** [comment]
- [x] HybridModel:Zone has no documentation in the IOref - *this is addressed in #7130*

The following are moved to #7760 

- ~~[ ] The organization of groups in the IOref does not always match the arrangement in the IDD!~~
- ~~[ ] The IDD group Natural Ventilation and Duct Leakage is shown in the IOref as AirflowNetwork~~
- ~~[ ] The IDD has Water Heaters and Thermal Storage group that includes thermal storage objects but they are described in the IOref under Plant Equipment~~
- ~~[ ] The IDD has Zone HVAC Air Loop Terminal Units group but in the IOref it is called Air Distribution Equipment~~
- ~~[ ] The IDD has one group called Humdifiers and Dehumidifiers but the IOref has two separate groups called Humidifiers and another called Desiccant Dehumidifiers~~

**Comment by mjwitte** [comment]
Reopening this - it was mistakenly closed via github magic. I think most of these have not been addressed.

**Comment by mitchute** [comment]
@mjwitte @Myoldmopar The Yahoo! user's group is dead, right? We should get it removed from [https://energyplus.net/support](https://energyplus.net/support)

**Comment by mjwitte** [comment]
@mitchute Not yet, the yahoo group is still there at the moment.

**Comment by mitchute** [comment]
@mjwitte I'm going to open a separate issue to track the Yahoo! user group. 

@JasonGlazer I'm moving these remaining open issues to a new doc-fix issue so this can wrap up soon. I think there's a chance we may need to reorder objects in the IDD to resolve these, but since we're so close to the IDD freeze I'd rather not take a chance in this not getting in.

**Comment by JasonGlazer** [comment]
@mitchute ok, I understand that the issues that I raised were complicated. It is probably worth a thorough review of the IDD and IOref.
