### ISSUE TITLE
Documentation Issues - 2019

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7160]
Issue overview
--------------
A collection of small documentation issues. See checkboxed comments below.

**Comment by mjwitte** [comment]
- [x] Input Output Reference, `EvaporativeCooler:Indirect:ResearchSpecial`, field Water Pump Power Modifier Curve Name says 
". . . If this input field is left blank, the pump power is assumed to be constant." 
This should say:
". . . If this input field is left blank, the pump power is assumed to vary linearly with the load.'
*Ref Helpdesk Ticket 13174*

**Comment by mjwitte** [comment]
- [x] Input Output Reference, `Tempering Valve`, typo highlighted below. *Moved here from #7121*
![storagew](https://user-images.githubusercontent.com/39242689/50863872-0ba4ac00-1355-11e9-9fa1-12dce71f50ed.PNG)

**Comment by mjwitte** [comment]
- [x] Input Output Reference, `TemperingValve`, more typos circled below. *Moved here from #7122*
![1012 typos](https://user-images.githubusercontent.com/39242689/50914713-06467080-13ec-11e9-8c47-2a2bb29f9f24.PNG)

**Comment by mldichter** [comment]
- [x] Typographical error "if" should be "of" in the following excerpt of the IO Reference.

![capture](https://user-images.githubusercontent.com/39242689/52443687-40825b00-2adb-11e9-98a7-9322d51889bb.PNG)

**Comment by mldichter** [comment]
Two (2) apostrophes missing in Fan:ZoneExhaust documentation.

![mising apostraphes](https://user-images.githubusercontent.com/39242689/52803186-65745200-3036-11e9-9c19-f6e1b6a993c5.PNG)

**Comment by mjwitte** [comment]
- [x] Engineering Reference, new heat emissions calculations (added for v9.1 in #7040 ), table "Heat Rejection Calculation for Different
HVAC Component Types" is not readable - wrong number of columns? Not sure. Source for table starts [here](https://github.com/NREL/EnergyPlus/pull/7040/files#diff-365bf065bb1c065e7d0919eb5e00eec4R83). It's rendering like this:
![image](https://user-images.githubusercontent.com/4991075/52980156-6d1d5900-339e-11e9-84ea-8eea41f51884.png)

*Addressed in https://github.com/NREL/EnergyPlus/pull/7203*

**Comment by mldichter** [comment]
In the Input Output Reference, there is mention of a "Passive component" and "Active component",

![active passive](https://user-images.githubusercontent.com/39242689/53512628-15ef4680-3a78-11e9-8f84-459e501b78b0.PNG)

but they don't seem to be mentioned anywhere else except for active component here.

![passive component](https://user-images.githubusercontent.com/39242689/53512644-1e478180-3a78-11e9-90b6-157e1e91604d.PNG)

Can there be a reference added for descriptions of these terms in this or another document?

**Comment by mldichter** [comment]
Text goes off the side of the page in IO Reference.

![off page](https://user-images.githubusercontent.com/39242689/53654848-92faf700-3c03-11e9-97ba-c95d4530a306.PNG)

**Comment by eringold** [comment]
In IO Reference, the AirConditioner:VariableRefrigerantFlow input field ['Heating Performance Curve Outdoor Temperature Type'](https://bigladdersoftware.com/epx/docs/9-0/input-output-reference/group-variable-refrigerant-flow-equipment.html#field-heating-performance-curve-outdoor-temperature-type) should indicate that for CondenserType = WaterCooled, the value should be 'DryBulbTemperature', else the heating performance curves will NOT be evaluated at condenser inlet water temperature. See: https://github.com/NREL/EnergyPlus/issues/5163, especially https://github.com/NREL/EnergyPlus/issues/5163#issuecomment-468734865.

**Comment by mldichter** [comment]
Text goes off the page.

![off page](https://user-images.githubusercontent.com/39242689/54140184-4ae88b00-43e0-11e9-9313-74e584021ef7.PNG)

**Comment by jmarrec** [comment]
* [x]  I/O ref for `CoilSystem:Cooling:DX:HeatExchangerAssisted` should be clear that it cannot be placed directly on an AirLoopHVAC (Branch) but wrapped inside a parent object (cf https://github.com/NREL/EnergyPlus/issues/7222)

**Comment by mldichter** [comment]
- [x] Should have 1.24.2.1.6 in front.

![typo](https://user-images.githubusercontent.com/39242689/54440338-b93a8f80-46f7-11e9-8daf-fbe4ddbbe622.PNG)

**Comment by mldichter** [comment]
- [x] Missing spaces

![space](https://user-images.githubusercontent.com/39242689/54440508-18000900-46f8-11e9-9a3e-b2ce648e6fe6.PNG)

**Comment by mldichter** [comment]
- [x] Typo RegiNe

![mn](https://user-images.githubusercontent.com/39242689/54440691-7331fb80-46f8-11e9-9dd7-a138ce0cb963.PNG)

**Comment by mldichter** [comment]
- [x] Inconsistent field names

![field names](https://user-images.githubusercontent.com/39242689/54441092-3d414700-46f9-11e9-90ca-e8e40d2acd00.PNG)

![io field names](https://user-images.githubusercontent.com/39242689/54441007-079c5e00-46f9-11e9-9b34-0c009e49fa38.PNG)

**Comment by mldichter** [comment]
- [x] This is a common typo of a missing apostrophe resulting in " s " in the input output reference. A search for " s " in the pdf resulted in 221 instances.

![esses](https://user-images.githubusercontent.com/39242689/54441890-db81dc80-46fa-11e9-98f3-58900401c946.PNG)

**Comment by mldichter** [comment]
- [x] Dollar signs present in equation

![dollar signs](https://user-images.githubusercontent.com/39242689/54628445-cb3b6b80-4a32-11e9-8e6b-dfeb5850b4a2.PNG)

**Comment by mldichter** [comment]
- [x] Text off side of page

![text off page](https://user-images.githubusercontent.com/39242689/54641205-d7cdbd00-4a4e-11e9-84e7-3509e9f48bab.PNG)

**Comment by mjwitte** [comment]
- [x] From user, helpdesk ticket 13193 (March 2019, so likely v9.0 Engineering Reference)

My own calculations, reproducing the Perez method as described in the Engineering Reference, agree with EnergyPlus results on surfaces of all tilts perfectly on fully overcast days and hours (i.e. those with direct normal radiation = 0 in the weather file). They're clearly missing the direct component, though, since they underestimate Isky as soon as direct normal radiation is present.

However, when I add in direct normal radiation on top of the sky radiance value, using the weather file's direct normal value and the same angular relationships as used in the sky radiance calculations, my total tends to be larger than the EnergyPlus result. I've double-checked my hourly cosine values with those output by EnergyPlus, and they agree very closely, so I don't think it's an error in the angle of incidence calculation.

Hi again,
I found the problem! And that is: there is a VERY misleading line in the Engineering Reference, Table 5.2, which describes the variables to be entered into the Perez model. There, the variable I-sub-h is called "Horizontal solar irradiance". (The units are also wrong - they should be W/m2, not W/m - and that's true for numerous variables in that table). Anyway - "Horizontal solar irradiance" typically means GLOBAL horizontal irradiance. However, it should read "DIFFUSE horizontal solar irradiance". This is not at all obvious and should be clarified

**Comment by MatthewSteen** [comment]
- [x] The LifeCycleCost:UsePriceEscalation object's [Year n Escalation](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/energyplus-economics/lifecyclecost-usepriceescalation.tex#L87) field should mention that if the `Length of Study Period in Years` field in the `LifeCycleCost:Parameters` object is greater than the number of years in this object, then the remaining year's escalation is set to 1.

**Comment by mjwitte** [comment]
- [x] Boiler:HotWater, I/O Ref. Input field  "Design Water Outlet Temperature" was removed for v9.0 (#6816) but the field name is still referenced in the descriptions of other fields (Nominal Thermal Efficiency and Design Water Flow Rate) and in the idf snippet.

**Comment by rraustad** [comment]
- [x] Noticed that some of these these report variable did not have a description. I was interested because I am getting 0's for Air System Simulation Maximum Iteration Count and Air System Simulation Iteration Count. It appears to me that these 2 accumulate controller iterations (even though it says "Air System ..."). I don't have any water coils with controllers. Maybe a name change is warranted (Air System Controller ...)? Or make these actually count air loop iterations. Regardless, someone (else) will want a description of these reports.

    1.26.1.2.2 HVAC System Solver Iteration Count []
    1.26.1.2.3 Air System Solver Iteration Count []
    1.26.1.2.4 Air System Simulation Maximum Iteration Count []
    1.26.1.2.5 Air System Simulation Iteration Count []
    1.26.1.2.6 Air System Component Model Simulation Calls []
      These variables are simply counters of how many iterations were executed. The count for any given
      HVAC time step will be the iterations executed before convergence was achieved, or the max allowed in
      which case the simulation throws a warning and proceeds to the next time step.

**Comment by mldichter** [comment]
- [x] The IO Reference for EnergyPlus 9.1 ZoneHVAC:EquipmentList example idf objects are missing the new fields.

![idf](https://user-images.githubusercontent.com/39242689/57416405-12cdb080-71b5-11e9-96cc-9a17c6666a3a.PNG)

![ioref](https://user-images.githubusercontent.com/39242689/57416409-1a8d5500-71b5-11e9-817b-dccc8a74c1bc.PNG)

**Comment by mldichter** [comment]
- [x] IO REF 9.1

![Capture](https://user-images.githubusercontent.com/39242689/57741298-13f95480-7671-11e9-9343-581d45b85cef.PNG)

**Comment by JasonGlazer** [comment]
- [x] InputOutputReference field names for CoolingTower:SingleSpeed do not match the field names used in the IDD.

**Comment by JasonGlazer** [comment]
- [x] InputOutputReference for EvaporativeCooler:Indirect:WetCoil describes the last two field Drift Loss Fraction and Blowdown Concentration Ratio but they are not actually supported by code and do not appear in the IDD. They should either but removed from the IORef or a new issue should be issued to add support these fields.

**Comment by rraustad** [comment]
- [x] Help desk ticket [15174](http://energyplus.helpserve.com/staff/Tickets/Ticket/View/15174).

The documentation for Controller:OutdoorAir in the Input Output Reference (pg 2058, Section 1.49.3) reads:

If all the limits are satisfied, the outdoor air controller does the following for continuous air flow systems:
if the outdoor air temperature is greater than or equal to the mixed air temperature setpoint, the outdoor
air flow rate is set to the maximum;

Shouldn't this say minimum?

**Comment by mjwitte** [comment]
@rraustad No, this is actually what the code is doing [here](https://github.com/NREL/EnergyPlus/blob/7a7082a357ad875ac3f0d9dd66564a85cae454d2/src/EnergyPlus/MixedAir.cc#L4495-L4500). If the limits are satisfied (which would include comparing against return air temp if that's the type of economizer operation), then the economizer is open.  It only throttles back if that would make the mixed air temp too cold,

**Comment by rraustad** [comment]
Not exactly. The damper is initially set to 1 at that place in code and then economizer limits are tested at lines 4501+. If they are satisfied, the damper is set to minimum and economizer disabled. So from how I read this, the text is backwards and appears to readers that the OA damper is wide open when OAT is higher than RAT.

**Comment by mjwitte** [comment]
The logic may seem backwards, but if none of the limits are tripped, then the economizer is active and fraction stays at 1.0 if `this->InletTemp > this->MixSetTemp`.

**Comment by RKStrand** [comment]
- [x] Whoever fixes these should also fix #7257 also

**Comment by JasonGlazer** [comment]
- [x] In the IOref 9.1, Shading:Fin and Shading:Fin:Projection use the term "overhang" when they should be using the term "fin". Probably just a pasteo from the overhang object documentation.

**Comment by RKStrand** [comment]
@mjwitte I'm not seeing this.  I'm seeing what is pasted below...
> [ ] Engineering Reference, new heat emissions calculations (added for v9.1 in #7040 ), table "Heat Rejection Calculation for Different
> HVAC Component Types" is not readable - wrong number of columns? Not sure. Source for table starts [here](https://github.com/NREL/EnergyPlus/pull/7040/files#diff-365bf065bb1c065e7d0919eb5e00eec4R83).

![image](https://user-images.githubusercontent.com/5804989/59629712-1257fc00-9109-11e9-840a-d9b51a352019.png)

**Comment by mjwitte** [comment]
@RKStrand That was addressed in https://github.com/NREL/EnergyPlus/pull/7203  - I checked it off above and added a note.

**Comment by Myoldmopar** [comment]
Closecx vcia #7359
