### ISSUE TITLE
Plant excessive heat storage tracking issues

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7931]
Issue overview
--------------
There are a few problems with the tracking for these warnings:
```
** Warning ** Plant Loop: CONDENSER WATER LOOP Demand Side is storing excess heat the majority of the time.
** Warning ** Plant Loop: CONDENSER WATER LOOP Supply Side is storing excess heat the majority of the time.
```
1. The supply side and demand side warnings are both testing the demand side data [here](https://github.com/NREL/EnergyPlus/blob/185e20e71c38982ae12f355ab950587cc20caa7f/src/EnergyPlus/Plant/PlantManager.cc#L4344-L4354).

2. `LoopSideInlet_CapExcessStorageTime` and `LoopSideInlet_TotalTime` accumulate on every plant iteration and during warmup. They should only accumulate after warmup and at the end of each system timestep.

3. Loops which are maintaining a constant loop supply temp are reporting non-zero values for " . . .  Plant Demand Side Lumped Capacitance Excessive Storage Time" (and Supply side).

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.3.0
 - Noticed this while working on #7653.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect files attached:
[5ZoneBoilerOutsideAirReset-ddays.idf.txt](https://github.com/NREL/EnergyPlus/files/4481072/5ZoneBoilerOutsideAirReset-ddays.idf.txt)
[PlantComponentTemperatureSource.idf.txt](https://github.com/NREL/EnergyPlus/files/4481073/PlantComponentTemperatureSource.idf.txt)

 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
5ZoneBoilerOutsideAirReset-ddays - The chilled water loop is well-controlled, yet it is reporting excessive storage time on both the demand side (occasionally) and supply side (always).
![image](https://user-images.githubusercontent.com/4991075/79334740-7cd2f780-7ee6-11ea-8ee5-c3d65ab6e6da.png)

**Comment by mjwitte** [comment]
PlantComponentTemperatureSource - similar results, but note how the Plant Supply Side Lumped Capacitance Excessive Storage Time is reporting values even when Plant Supply Side Lumped Capacitance Heat Storage Rate is zero:
![image](https://user-images.githubusercontent.com/4991075/79335455-ab9d9d80-7ee7-11ea-8264-2ec161e13fb8.png)

And this file throws warnings:
```
   ** Warning ** Plant Loop: MAIN LOOP Demand Side is storing excess heat the majority of the time.
   ** Warning ** Plant Loop: MAIN LOOP Supply Side is storing excess heat the majority of the time.
```

**Comment by mjwitte** [comment]
@Myoldmopar @EnergyArchmage With the supply side warnings active (actually checking supply side data), normal operating conditions can tally excessive storage time. For example when the load on the loop is increasing, then the storage node leaving the demand side will rise. Or when the loop setpoint is not fixed, and it rises, then the storage node leaving the supply side will rise. Both of these conditions will count excessive storage time.

The old rule was:
```
if (PlantLoop(LoopNum).LoopSide(TankOutletLoopSide).LoopSideInlet_MdotCpDeltaT < PlantLoop(LoopNum).LoopSide(TankOutletLoopSide).LoopSideInlet_McpDTdt) {
```
The current proposed rule in #7932 is:
```
if ((side.LoopSideInlet_McpDTdt > DataHVACGlobals::SmallLoad) &&  (abs(side.LoopSideInlet_MdotCpDeltaT) < side.LoopSideInlet_McpDTdt)) {
```
This weeds out times when there is a tiny storage change or when the loop transport is the opposite sign of the storage.

I'm considering adding some additional constraints to avoid false counts for increasing load and increasing setpoint. 

For the setpoint case, the rule could check the outlet vs loop setpoint and if it's within some temperature tolerance, the it's not excessively storing.

For the increasing load case, I'm not sure.

Was the original intent to trap a loop that's overheating or a loop where the storage volume is too large or ?

**Comment by EnergyArchmage** [comment]
> For the setpoint case, the rule could check the outlet vs loop setpoint and if it's within some temperature tolerance, the it's not excessively storing.

This reminds me of the plant loop unmet hours reporting I recently added for parallel branch study. Just add up the time that setpoint is not met.  

> Was the original intent to trap a loop that's overheating or a loop where the storage volume is too large or ?

Main goal was to identify when loop thermal storage was serving loads.  maybe loads are very low and the supply equipment is not running, maybe the loop volume is very high relative to the flow.  Excessive loop temperatures are flagged separately.
