### ISSUE TITLE
Documentation Issues 2021a

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#8277]
Issue overview
--------------
A place to collect documentation issues.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mitchute** [comment]
- [x] See here: https://github.com/NREL/EnergyPlus/issues/7949#issuecomment-692795398
This may require output changes.

**Comment by mitchute** [comment]
- [x] "Useh by EnergyPlus"

https://github.com/NREL/EnergyPlus/blob/develop/doc/auxiliary-programs/src/weather-converter-program/definitions-file-custom-file-processing.tex#L312

https://github.com/NREL/EnergyPlus/blob/develop/doc/auxiliary-programs/src/weather-converter-program/definitions-file-custom-file-processing.tex#L318

**Comment by jmythms** [comment]
- [x] Posting this issue from #7760 here, requesting comments on how to handle it. 

https://github.com/NREL/EnergyPlus/issues/7760#issuecomment-585356366
@jasondegraw @jasondegraw

**Comment by mitchute** [comment]
@JasonGlazer FYI the above comment: https://github.com/NREL/EnergyPlus/issues/8277#issuecomment-696236954

**Comment by shorowit** [comment]
- [x] https://bigladdersoftware.com/epx/docs/9-3/input-output-reference/group-surface-construction-elements.html#field-shade-to-glass-distance "Note used for between-glass shades." should presumably be "**Not** used for between-glass shades."

**Comment by jcyuan2020** [comment]
- [x] For the PCM peak freezing temperature description in Sec 1.9.9.1.13 (page 163, InputOutput Reference.pdf, v9.4), it was reported that the description says that it will be higher than the peak melting temperature while it was believed to be the opposite. After turning up a couple of literature resources, it seems that the the empirical data and plots found in the literature show a higher peak melting temperature than the peak freezing temperature for the materials reported in the literature.

It was also reported that the testfile example ``1ZoneUncontrolledWithHysteresisPCM.IDF`` case actually contains PCM entries that show a peak freezing temperature of 23 C but a peak melting temperature of 20 C.

Ref to Helpdesk ticket number 15566

If changes above are confirmed, then the idf code block example in Page 163 of I/O Reference (v9.4) would also update for the relationship for the peak melting temperature and the peak freezing temperature shown in this example block.

**Comment by jmythms** [comment]
- [x] Edit for clarity: (pg 1503, IORef 9.4, [source link](https://github.com/NREL/EnergyPlus/blob/111e8bd920fddbf4969ec4c43ed931a02bdbb31c/doc/input-output-reference/src/overview/group-radiative-convective-units.tex#L1288))The constant flow system differs from the **variable flow system described** above in what it controls. The **variable flow system** varies the flow...

**Comment by jmythms** [comment]
- [x]  (pg 1487, IORef 9.4, [source link](https://github.com/NREL/EnergyPlus/blob/111e8bd920fddbf4969ec4c43ed931a02bdbb31c/doc/input-output-reference/src/overview/group-radiative-convective-units.tex#L699)): A missing headline that the text that follows belongs to outputs. (Outputs for ZoneHVAC:CoolingPanel:RadiantConvective:Water. )

**Comment by jmythms** [comment]
- [x] (pg 1476 & 1479, IORef 9.4, source links: [Link 1](https://github.com/NREL/EnergyPlus/blob/111e8bd920fddbf4969ec4c43ed931a02bdbb31c/doc/input-output-reference/src/overview/group-radiative-convective-units.tex#L294), [Link 2](https://github.com/NREL/EnergyPlus/blob/111e8bd920fddbf4969ec4c43ed931a02bdbb31c/doc/input-output-reference/src/overview/group-radiative-convective-units.tex#L451)): The "Note on Fraction of Radiant Energy Incident on People and to Surfaces" should not be part of the inputs. Suggest that they look like similar text on pg 1471 ([source](https://github.com/NREL/EnergyPlus/blob/111e8bd920fddbf4969ec4c43ed931a02bdbb31c/doc/input-output-reference/src/overview/group-radiative-convective-units.tex#L108)).

**Comment by mitchaldichter** [comment]
- [x] The IO Ref description for the "Availability Manager List Name" of the AirLoopHVAC:OutdoorAirSystem object is ambiguous and the IDD does not mention if the field is optional or not in use.

![inconsisteent](https://user-images.githubusercontent.com/73209151/98572950-13904880-226b-11eb-9b16-d479db059ee8.PNG)

![ignosed](https://user-images.githubusercontent.com/73209151/98573028-2f93ea00-226b-11eb-88f4-4252298e0d83.PNG)

**Comment by MatthewSteen** [comment]
__Input Output Reference - Coil:Cooling:DX:SingleSpeed:ThermalStorage__

- [x] [Field: Operation _Mode_ Control Schedule Name](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex#L8281) model should be _mode_ in the description.

> This field is used (and required) if the operating _model_ control method is set to ScheduledModes in the previous input field.

**Comment by MatthewSteen** [comment]
__Input Output Reference - WindowShadingControl__

- [x] [Field: Shading Control Type](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex#L4178) is missing the description for the following control types.

* OnIfHighZoneAirTempAndHighSolarOnWindow
* OnIfHighZoneAirTempAndHighHorizontalSolar

- [x] [Field: Setpoint 2](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex#L4295) number of control types is incorrect, suggest simply removing __two__.

> Used only as the second setpoint for the following __two__-setpoint control types: OnIfHighOutdoorAirTempAndHighSolarOnWindow, OnIfHighOutdoorAirTempAndHighHorizontalSolar, OnIfHighZoneAirTempAndHighSolarOnWindow, and OnIfHighZoneAirTempAndHighHorizontalSolar

**Comment by shorowit** [comment]
- [x] EMS actuators are missing from the EMS Application Guide. Specifically I noticed [these four surface actuators](https://github.com/NREL/EnergyPlus/blob/a9778bafea2ee3e92c6671144fa08d1394f11099/src/EnergyPlus/EMSManager.cc#L2166-L2191) missing, though it might be worth auditing all of the EMS actuators, sensors, and internal variables in the source code to make sure they are documented.
The original three of these were present in the v8.2 documentation, so they got lost along the way. Here's the pdf so one can grab the text.
[v8.2 EMS Application Guide Surface Actuators.pdf](https://github.com/NREL/EnergyPlus/files/5817422/v8.2.EMS.Application.Guide.Surface.Actuators.pdf)

*Addressed in #8477*

**Comment by shorowit** [comment]
- [x] The [documentation for Output:EnergyManagementSystem](https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/input-for-output.html#outputenergymanagementsystem) has references to "NotByUniqueNames", but it should be "NotByUniqueKeyNames" according to the IDD.

**Comment by jcyuan2020** [comment]
- [x] Section 1.41.21.1.6, Page 1823 of I/O Reference (v9.4):  for the Coil:Heating:DX:SingleSpeed, the field name ``Rated Evaporator Fan Power Per Volume Flow Rate`` should consider using a better name, as for the heating coil, theoretically it should be referring to the "condenser" fan. 
![image](https://user-images.githubusercontent.com/64040111/105060321-dd76fe00-5a3d-11eb-8fe4-848e561d739a.png)

Actually for Energy+.idd file, the description says ``Rated Supply Fan Power Per Volume Flow Rate``
![image](https://user-images.githubusercontent.com/64040111/105061095-ba991980-5a3e-11eb-8f44-24d752e3f873.png)

So in the documentation Section 1.41.21.1.6, it is suggested to use "Supply Fan" as well instead of "Evaporator fan". 

ref to helpdesk ticket # 15614

**Comment by shorowit** [comment]
- [x] Remove references in the documentation to updating the IDD. As [stated here](https://github.com/NREL/EnergyPlus/issues/8455#issuecomment-763034918), "Neither the idd nor the schema file are read at runtime. The schema is embedded into the EnergyPlus binary so a user cannot modify either idd or schema and expect any effect.". Here are a couple examples ([one](https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-water-heaters.html#field-number-of-nodes-000) and [two](https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-air-distribution.html#field-set-availability-manager-object-type-name)) where the documentation says the IDD can be updated for additional capability, but this is no longer true. There are likely others.

**Comment by eringold** [comment]
- [x] Engineering Reference references old 'Fan:Simple' objects in 16.7 Variable Refrigerant Flow Heat Pumps:
 https://github.com/NREL/EnergyPlus/blob/33aabb828e046ed1344b4dc8daee64d27737d888/doc/engineering-reference/src/simulation-models-encyclopedic-reference-002/variable-refrigerant-flow-heat-pumps.tex#L48

**Comment by RKStrand** [comment]
- [x] Equation 1.14 on page 186 of the IORef for custom window properties appears to be incorrect.  The equation shown is linear, but the coefficients shown after the equation clearly indicate that there should be a second order term.
<img width="609" alt="image" src="https://user-images.githubusercontent.com/5804989/107799817-8eae4280-6d23-11eb-8db6-d97bdd0b68a7.png">

**Comment by RKStrand** [comment]
- [x] Another issue from window stuff in the IORef.  In the image below, notice that the example uses Material:WindowGlass which is not in the IDD.  The example needs to be fixed--the list of input fields does not match the current list for WindowMaterial:Glazing.
<img width="609" alt="image" src="https://user-images.githubusercontent.com/5804989/107855153-5b80b780-6de6-11eb-8fe6-94beb39d76c9.png">

**Comment by jcyuan2020** [comment]
- [x]  I/O Ref document (v9.4.0) Page 1365: 

The `Field: Supply Fan Operating Mode Schedule Name` should be in the same level as Section 1.32.5.4. See the following highlighted and italicized part:
![image](https://user-images.githubusercontent.com/64040111/107863078-ea0d2d00-6e16-11eb-917a-9eecb9ee710d.png)

**Comment by MatthewSteen** [comment]
- [x] __EnergyPlus Weather File (EPW) Data Dictionary__
    ...The Design Conditions header record encapsulates matching (using WMO# – World Meteorological Organization Station Number) design conditions for a weather file location. Currently only those design conditions contained in the ASHRAE Handbook of Fundamentals 2009 are contained in the weather files. These conditions can be used as desired. In addition, Design Day definition files have been created of all World, Canada, and United States Design Conditions. [_These files are available in the DataSet folder of the EnergyPlus installation._](https://github.com/NREL/EnergyPlus/blob/develop/doc/auxiliary-programs/src/weather-converter-program/energyplus-weather-file-epw-data-dictionary.tex#L116)

These files are not in my v9-4-0 Windows installation.

*MJW - If it was there, it should be in the **Macro**DataSets folder. Locations-DesignDays.xls is included there, but it's corrupt and the best Excel can do with it is open empty tabs.*

**Comment by RKStrand** [comment]
- [x] GettingStarted.pdf p.45:
At the end of this page, Section 5.2.4 starts and then goes into a list.  The list however is cut-off/runs off the bottom of the page.  Two pages that are completely filled with images follow.  Then, the next text which shows up is Section 5.2.5.1 at the top of p. 48.  Clearly, there are some things that are missing from this document (the rest of Section 5.2.4 and the start of 5.2.5).  This needs to be addressed.

**Comment by jcyuan2020** [comment]
- [x] The phase change material finite difference model has an output named ``CondFD Phase Change State``, with values from -2 to 2. However, the meaning of these numbers are not documented in the documentations. After looking up the source code, the integers are corresponding to the following state: 
```
-2 = LIQUID;
-1 = MELTING;
0 = TRANSITION;
1 = FREEZING;
2 = CRYSTALLIZED;
```
Some explanations should be added to this output values in the appropriate PCM sections (e.g Section 1.9.8 or Section 1.9.9). 

ref to helpdesk ticket# 15663

**Comment by mjwitte** [comment]
- [x] Input Output Reference for WindowProperty:FrameAndDivider has "Figure ??" in several places. (v9.5.0 IOFreeze).

_RKS: @mjwitte I didn't find any "Figure ??" in this section and all of the occurrences of "Figure" in this section have a valid figure number and link.  All the links go to the right place.  So, I think this is already fixed._

**Comment by shorowit** [comment]
- [x] Input Output Reference for Coil:Heating:Gas:MultiStage says "For the time being, this coil model can only be called by the parent object AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed.", but IDD shows that it can be used with AirLoopHVAC:UnitarySystem.

**Comment by mitchute** [comment]
- [x] Address #7006

**Comment by mitchute** [comment]
- [x] Maybe address #6974, but that might be too much for this task.

_RKS: Took some time, but I have now gone through ALL of the EMS actuator calls in the code and have corrected all of their appearances in the EMS docs._

**Comment by mitchute** [comment]
- [x] Noting #4306 here. Move it to a new docs PR if it doesn't get addressed in this go-round.

**Comment by jcyuan2020** [comment]
- [x] Page 111 in InputOutputReference.pdf (v9.5), Figure 1.8: The figure is actually for ground domain basement. However, the caption of the figure says it is "on-grade" configuration, which is incorrect:

![image](https://user-images.githubusercontent.com/64040111/120684665-96c1f780-c464-11eb-8250-e995f1e567bb.png)


Ref to Issue #7881 and helpdesk ticket 15723.

_RKS--The issue here is that the figure is wrong.  For some reason, this figure is a duplicate of the basement that is shown in the next figure (Figure 1.9).  Either the correct figure needs to be tracked down or a new one created._

**Comment by eringold** [comment]
- [x] InputOutputReference describes MaterialProperty:PhaseChangeHysteresis inputs 'Peak Melting Temperature', 'Peak Freezing Temperature' as "in Kelvin", but EnergyPlus idd lists the units for these fields as `\units C`.

**Comment by RKStrand** [comment]
This issue is now being worked on.  For any further documentation issues, please start a new issue.  Thanks!

**Comment by RKStrand** [comment]
@jasondegraw @JasonGlazer @jmythms @mitchute @mjwitte 
Any progress on the issue listed here regarding the following?

https://github.com/NREL/EnergyPlus/issues/7760#issuecomment-585356366

**Comment by mitchute** [comment]
Nothing from me. I'll defer to @jasondegraw and @mjwitte on the right direction to go.
