### ISSUE TITLE
EnergyPlus 9.6 Release Checklist

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#9056]
Remaining items for 9.6, will be added to as we find them:
 - [x] Remaining PRs merged/punted/closed
 - [x] Deprecation document into release package
 - ~Deprecation email sent to stakeholders~  This can be done with the release out, not required for before.
 - [x] Updated Helpdesk link in readme, anywhere in documentation?
 - [x] Update README
 - [x] Run EPTravisTester - success! https://app.travis-ci.com/github/Myoldmopar/EPTravisTester/builds/238300048
 - [x] Update SetupOutputVariables
 - [x] Update header in Report Variables doc

**Comment by mjwitte** [comment]
I don't think it matters since there aren't any output variable name changes this release, but the first line of [Report Variables 9-5-0 to 9-6-0.csv](https://github.com/NREL/EnergyPlus/blob/develop/src/Transition/SupportFiles/Report%20Variables%209-5-0%20to%209-6-0.csv)  still has 10.0 instead of 9.6.

**Comment by Myoldmopar** [comment]
Closed via #9088
