### ISSUE TITLE
Create an Installer Testing Checklist

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#9350]
Issue overview
--------------
Create a markdown checklist that anyone can use to test installers. This would include a list of various applications to start and what to do to test each application. It would also include some spot checking of the documentation. Specific files to test would include ones that require various add-ons like preprocessors. Hopefully, the list could be something that someone could walk through in an hour or less. This could be made part of the EnergyPlus wiki. GARD had a very old version of such a checklist but it is extremely out of date.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
This is good of course, but wherever possible, steps should be added to the automated installer testing tool: https://github.com/Myoldmopar/EPTravisTester/.

(It is now named incorrectly because it uses GitHub actions instead of Travis, but anyway...)

It already tests multiple E+ runs, including API calls, Python files, workflows that exercise the auxiliary Fortran tools, etc.  The things that are difficult to check on there are obviously the graphical tools like EPLaunch, so the manual installer checklist should definitely focus on those things.
